### ISSUE TITLE
Add Validation for Empty Fields and Display Alert Message

### ISSUE THREAD

**Issue by amol-rathod-147** [amol-rathod-147/Amol-To-Do-List#17]
- When the user tries to add a task, check if any of the input fields (task, date, or time) are empty.
- If any field is missing, display a message saying "Please fill in all fields."
- The message should be shown above the form with a close button.
- Ensure the message is styled to match the provided design: yellow background, dark text, and a green "OK" button.
- Prevent further execution if any of the fields are empty.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified index.html to include an error message container and updated script.js to check for empty fields, display an error message, and prevent task addition when fields are empty.

You can review changes in this commit: https://github.com/mnmnk43434/amol-rathod-147-Amol-To-Do-List-17/commit/6dc0e58e03f68b651567d224a6d326c88fe87849.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
